### ISSUE TITLE
timer

### ISSUE THREAD

**Issue by GeneralSpancake** [geheur/clue-juggling-timers#2] opened 2024-03-06 12:15 UTC
timer clues is incorrect should be 1 hour

**Comment by DrYoshiyahu** [comment] 2024-03-06 12:46
I'm pretty sure this is not something that will be fixed with this plugin directly. This plugin gets the despawn timer from Runelite itself. Specifically the `EventBus`. Once Runelite adjusts the despawn timer for the clue scrolls, this plugin will continue to work as intended.

**Comment by Septem151** [comment] 2024-03-06 13:26
@DrYoshiyahu this plugin uses an internal mechanism for drop timers found within [GroundItemPluginStuff](https://github.com/geheur/clue-juggling-timers/blob/1c343de9624823e4fd184df626178d2569dc7b3c/src/main/java/com/cluejuggling/GroundItemPluginStuff.java)

Setting the drop timer to 1 hour fixes this. I also added some additional formatting since the timer would always display in seconds leading to some text overflow in the infoboxes.

**Comment by geheur** [comment] 2024-03-09 03:20
There is now a 1 hour timer.

**Closed by geheur** 2024-03-09 03:20 UTC
